=== shubham-123-els/beautyroute_elsner/app/code/FishPig/WordPress/etc/wordpress_core.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="urn:magento:module:Magento_Catalog:etc/product_types_base.xsd" />

    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="group" type="wpCoreGroupDeclaration" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
        <xs:unique name="uniqueGroupName">
            <xs:selector xpath="group" />
            <xs:field xpath="@id" />
        </xs:unique>
    </xs:element>
    <xs:complexType name="wpCoreGroupDeclaration">
        <xs:all minOccurs="0">
            <xs:element name="depends" type="wpCoreGroupDependsDeclaration" minOccurs="0" />
            <xs:element name="globalVariables" type="wpCoreGlobalVariablesDeclaration" minOccurs="0" />
        </xs:all>
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="wpCoreGlobalVariablesDeclaration">
        <xs:sequence>
            <xs:element name="var" type="wpCoreGlobalVariablesVarDeclaration" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="wpCoreGlobalVariablesVarDeclaration">
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="wpCoreGroupDependsDeclaration">
        <xs:all minOccurs="0">
            <xs:element name="plugin" minOccurs="0">
                <xs:unique name="uniquePluginFileName">
                    <xs:selector xpath="plugin" />
                    <xs:field xpath="@file" />
                </xs:unique>
            </xs:element>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== shubham-123-els/beautyroute_elsner/app/code/FishPig/WordPress/etc/wordpress_core.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="wordpress_core.xsd">
    <group id="core">
        <globalVariables>
            <var name="post"/>
        </globalVariables>
    </group>
    <group id="revslider">
        <depends>
            <plugin file="revslider/revslider.php"/>
        </depends>
        <globalVariables>
            <var name="revSliderVersion"/>
            <var name="rs_wmpl"/>
            <var name="rs_slider_serial"/>
            <var name="rs_ids_collection"/>
            <var name="rs_material_icons_css"/>
            <var name="rs_material_icons_css_parsed"/>
            <var name="revslider_fonts"/>
            <var name="rs_double_jquery_script"/>
        </globalVariables>
    </group>
    <group id="prismatic">
        <depends>
            <plugin file="prismatic/prismatic.php"/>
        </depends>
        <globalVariables>
            <var name="prismatic_options_general"/>
            <var name="prismatic_options_prism"/>
            <var name="prismatic_options_highlight"/>
        </globalVariables>
    </group>
    <group id="copy-delete-posts">
        <depends>
            <plugin file="copy-delete-posts/copy-delete-posts.php"/>
        </depends>
        <globalVariables>
            <var name="cdp_plug_url"/>
        </globalVariables>
    </group>
    <group id="accelerated-mobile-pages">
        <depends>
            <!-- The spelling mistake here (moblie) is from the plugin devs, not me! -->
            <plugin file="accelerated-mobile-pages/accelerated-moblie-pages.php"/>
        </depends>
        <globalVariables>
            <var name="fontComponent"/>
            <var name="scriptComponent"/>
            <var name="loadComponent"/>
            <var name="redux_builder_amp"/>
            <var name="moduleTemplate"/>
            <var name="layoutTemplate"/>
            <var name="savedlayoutTemplate"/>
            <var name="containerCommonSettings"/>
            <var name="post_type"/>
            <var name="ampforwpTemplate"/>
            <var name="ampLoopData"/>
            <var name="counterOffset"/>
            <var name="amp_q"/>
            <var name="amp_icons_css"/>
            <var name="supportComponent"/>
        </globalVariables>
    </group>
</config>
